config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  root 'articles#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
  if @article.save
    redirect_to articles_path
  else
    render :new
  end
  end

  def show
    @article = Article.find(params[:id])
  end

private
  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>Hello, kindeditor.interesting things</h1>
<br>
<div>
    <%= link_to("New article", new_article_path) %>
  </div>
<br><br>
<table>
    <thead>
      <tr>
        <td>Title</td>
        <td>content</td>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to(article.title, article_path(article)) %></td>
          <td><%= raw article.content %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/articles/new.html.erb
<div>
    <h2>新增文章add new article</h2>

    <hr>
    <%= form_for @article do |f| %>

    标题title
    <br>
    <%= f.text_field :title %>
    <br>
    内容content
    <br>
    <%= f.kindeditor :content %>
    <br>

    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end %>

</div>

app/views/articles/show.html.erb
<div>
  <h2><%= @article.title %></h2>
  <p><%= raw @article.content %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Company</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>